export enum MATCH_EVENT_TYPE {
    GOAL = 1,
    GOAL_FROM_PENALTY = 2,
    FAILED_PENALTY = 3,
    PENALTY_2_MINUTES = 4,
    YELLOW_CARD = 5,
    RED_CARD = 6,
    RED_CARD_PLUS = 7,
    BLUE_CARD = 8,
    TEAM_TIME_OUT = 9,
}
